<?php require "calculation-sections.php"; ?>

<?php displayArrayAsList($calculation_details); ?>

<?php if (!empty($summary) || !empty($calculation) || !empty($inputs)): ?>


    <?php if (!empty($summary)): ?>

        <h2>Calculation Summary</h2>

        <?php displayArrayAsList($summary); ?>

    <?php endif; ?>



    <?php if (!empty($calculation)): ?>

        <h2>Calculation Details</h2>

        <details>

            <summary>Detailed Tax Calculation</summary>

            <div class="print-container">

                <?php displayArrayAsList($calculation); ?>

                <?php include ROOT_PATH . "views/shared/print-button.php"; ?>

            </div>

        </details>

        <br>

    <?php endif; ?>


    <?php if (!empty($inputs)): ?>

        <details>

            <summary>Calculation Inputs</summary>

            <div class="print-container">

                <?php displayArrayAsList($inputs); ?>

                <?php include ROOT_PATH . "views/shared/print-button.php"; ?>

            </div>

        </details>

        <br>

    <?php endif; ?>

    <form action="/self-assessment-assist/produce-report" method="GET">

        <input type="hidden" name="calculation_id" value="<?= esc($calculation_id) ?>">

        <button class="link" type="submit">View HMRC Assist Messages</button>
    </form>


    <!-- if submitting -->
    <?php if (isset($show_submit) && $show_submit === true): ?>

        <br>

        <?php if ($calculation_details['calculationType'] === "intent-to-finalise"): ?>

            <h2>Submit Your Final Declaration to HMRC</h2>

        <?php elseif ($calculation_details['calculationType'] === "intent-to-amend"): ?>

            <h2>Submit Your Amended Final Declaration to HMRC</h2>

        <?php endif; ?>



        <?php include "submission-form.php"; ?>

        <p><a href="/obligations/final-declaration">Cancel</a></p>

    <?php endif; ?>



<?php else: ?>

    <p>No calculation is available to display.</p>

<?php endif; ?>

<!-- if in-year calculation: -->
<?php if (!isset($hide_calculation_options) || empty($hide_calculation_options)): ?>

    <h2>Change Your Calculation</h2>

    <p>Your tax calculation is generated by HMRC. To change the calculation, submit new or updated information to HMRC.</p>


    <p>The calculation is not final until you submit a Final Declaration after the end of the tax year. In-year
        calculations are simply estimates provided by HMRC and may not accurately represent the final amount of
        tax due calculated after the end of the tax year.</p>


    <p><a href="/individual-calculations/trigger-calculation">Click here</a> to generate a new calculation</p>

    <p><a href="/business-details/list-all-businesses">Click here</a> to submit a new summary or adjustments for a business.
    </p>

    <p><a href="/submissions/get-submissions">Click here</a> to view submissions made for this tax year.</p>


    <h3>Loss Relief</h3>

    <p>Sideways loss relief against income from the same tax year cannot be claimed until after the end of the year.</p>

    <p>If you are claiming sideways relief and the relief is not shown in your calculation,
        make sure you have claimed the loss, which you can do
        by selecting the business which made the loss <a
            href="/business-details/list-all-businesses?year-end=true">here</a>.
    </p>



    <p><a href="/individual-losses/list-loss-claims">View all losses</a></p>

    <p><a href="/individual-losses/edit-loss-claim-sequence">Click here</a> to change the order in which sideways loss
        claims are applied to your calculation, if you have more than one.</p>

    <p><a href="/individual-losses/list-brought-forward-losses">Click here</a> to view all losses brought
        forward from before you joined Making Tax Digital.
    </p>

<?php endif; ?>


<?php $include_print_script = true; ?>